README.md
module-options.nix

In its current form, `find_up` passes an invalid value for `$tree_root` to `treefmt`, resulting in the following error:
```
.nixpkgs on  master [$✘!+⇡] via ❄️  impure (devshell) on ☁️  snip
❯ treefmt -v
[DEBUG]: tree_root=/Users/kclejeune/.nixpkgs/flake.nix work_dir=/Users/kclejeune/.nixpkgs cache_dir=/Users/kclejeune/Library/Caches/com.NumTide.treefmt/eval-cache config_file=/nix/store/mwiijsrkrcnggq1gn6zvz7sj60pb0812-treefmt.toml paths=["/Users/kclejeune/.nixpkgs/flake.nix"]
[DEBUG]: load config: 167.79µs (Δ 167.79µs)
[DEBUG]: Found /nix/store/7hwn4c79z2gi97br6d6gmmq2mnakbcvx-alejandra-3.0.0/bin/alejandra at /nix/store/7hwn4c79z2gi97br6d6gmmq2mnakbcvx-alejandra-3.0.0/bin/alejandra
[DEBUG]: built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required …
```

fix: correct find_up to print root dir instead of file path

---

programs/rustfmt.nix

rustc package actually does not contain rustfmt.

rustfmt: fix package

---

README.md
default.nix
flake-module.nix
flake.nix
module-options.nix

I'm opening a draft PR (instead of waiting for full implementation) just to get something working, as well as to get any early feedback. The commits in this PR can be squash merged (or I can rebase them if necessary) once ready.
This PR adds a `flake-parts` module for working with treefmt in the most ergonomic way. It also adds a flake check to test in CI that the source tree is formatted. You can see a demo here: https://github.com/srid/haskell-template/pull/75
Resolves #1

Add `flake-parts` module

---

README.md
programs/stylish-haskell.nix

People usually use stylish-haskell over ormolu (despite my own preferences). I added my own config and thought it'd be nice to contribute upstream.
@zimbatm+team: Please review these changes and LMK if they are appropriate.

Add stylish-haskell

---

bors.toml
flake-module.nix

Merge https://github.com/numtide/treefmt-nix/pull/28 first

flake-module: enable treefmt as default formatter for the flake

---

flake-module.nix

This should make the docs render again.
`lib.mdDoc` isn't needed here. Flake-parts skips the docbook migration, so everything is already markdown.

flake-module.nix: Fix doc

---

README.md
programs/hlint.nix

feat: add programs.hlint

---

README.md
programs/buildifier.nix

a bazel formatter
I've tried using this PR on a bazel project but I get:
```
[INFO]: Error using formatter #buildozer:
• [STDOUT]:
• [STDERR]:
/home/teto/nova/BUILD.bazel: error while executing commands [] on target /home/teto/nova/buildlib/default_extensions.bzl
```
I used to run `buildozer -r .`, how does treefmt run commands ? does it pass a
list of them to the "command" or does it call the binary for each file ?

feat: add buildifier

---

programs/ocamlformat.nix

Note
---
There is no way to pass in config file, ``--config`` takes in manually placed options, not ``.ocamlformat`` files.

[ocamlformat]: Version detection

---

programs/ocamlformat.nix

My bad, forgot to trim the values to support spaced cases
e.g
```ocamlformat
version =  0.24.1
```

[ocamlformat]: trim option/value

---

programs/ocamlformat.nix
run-tests.sh

This makes sure that the docs can be rendered.
The error was as follows, excluding the stack trace:
```
error: Most nixpkgs attributes are not supported when generating documentation.
Please check with `--show-trace` to see which option leads to this `pkgs.AAAAAASomeThingsFailToEvaluate` reference. Often it can be cut short with a `defaultText` argument to `lib.mkOption`, or by escaping an option `example` using `lib.literalExpression`.
```

Fix and check docs

---

module-options.nix

devShell default value could not be rendered.
As a readOnly option, it only allows a single definition, so the priority does not matter.
The simplest solution is to make the definition not an option default so that its value is not rendered.
One day I'll add CI for the docs; need to work on the OSS use case a bit.

Fix option docs rendering

---

flake-module.nix
flake.lock

Without this, the flake check hardcodes `self`.
This is used here: https://github.com/srid/haskell-flake/pull/179 where the CI is building a subflake, whose treefmt needs to format files from repo root.

flake-parts: Allow configuring project root

---

README.md

Just happened across this project but the flake directions in `README.md` didn't work as `evalModule` is under the `lib` attribute and the example `./treefmt.nix` file should be an attrset (based on this repo's own file) not a function.

Fix flakes syntax in README.md

---

examples/formatter-shfmt.toml
programs/shfmt.nix

So the defaults don’t get in the way of reading the config file.
Fixes #96.

Allow indent_size to be unset for shfmt

---

README.md

`${pkgs.sytem}` -> `${pkgs.system}`

Fix minor type in README

---

programs/dhall.nix

This also makes some other minor changes to the Dhall module.

dhall: Add support for `lint`

---

README.md

readme: flake-parts: update link

---

README.md

I think this could be documented as part of the readme.
Closes https://github.com/numtide/treefmt-nix/issues/111

readme: document how to use custom formatters

---

examples/formatter-elm-format.toml
programs/elm-format.nix

This change allows to pass a list of `includes` to the `elm-format` configuration and is an addition after #163.
I want to add this configuration option because in a project I generate a lot of Elm code from another tool. Those generated files are not checked in into source control and don't fully follow the `elm-format` code formatting.
With this change, I can pass include rules that allow me to only format the files that are actually part of the repository and ignore the generated files.
```nix
programs.elm-format.enable = true;
programs.elm-format.includes = [ "src/Main.elm" ];
```
Thank you for your time and for creating this tool.  
I'm not sure if the desired approach is to immediately create a PR, or first discuss why I would like to add this change.
I copied the code from the …

Configurable includes for elm-format

---

examples/formatter-elm-format.toml
programs/elm-format.nix

The formatting of the elm-format configuration contained additional whitespace due to which formatting did not pick up on the files.

Fix elm-format

---

programs/csharpier.nix

- **add nixfmt-rfc-style**
- **flake update**
- **add fantomas (#159)**
- **feat(programs): add templ (#161)**
- **feat(programs): add opa (#162)**
- **Fix elm-format**
- **Add changed `examples/formatter-elm-format.toml`**
- **Make elm-format `includes` configurable**
- **feat(programs): add dos2unix (#165)**
- **fix(programs): leptosfmt does not touch files anymore (#166)**
- **feat: add ts declaration extensions to ext.js (#168)**
- **Add `packer fmt` formatter (#169)**
- **add includes and excludes options for csharpier**

csharpier extensions

---

examples/formatter-php-cs-fixer.toml
programs/php-cs-fixer.nix

This fixes an issue with php-cs-fixer, where it throws an error about requiring the `--config` argument if multiple files to format are specified.

php-cs-fixer: add configFile option

---

checks/default.nix
module-options.nix

Allows for experimenting with new config options in `treefmt` without having to update `treefmt-nix`, whilst at the same time retaining types for stable config options.
Will allow passing pipeline related options for `2.0.0-rc1` for example.

feat: make treefmt settings a freeform type

---

examples/formatter-hclfmt.toml
programs/hclfmt.nix

Avoid clashes with the `terraform` formatter who does a better job at formatting the ".tf" files, since it has more domain knowledge there.

hclfmt: only format .hcl files

---

examples/formatter-actionlint.toml
programs/actionlint.nix

Sorry, I think I misunderstood the way actionlint consumes the actions.yml files. It looks like passing the files directly isn't intended for actions.
> actionlint still focuses on checking workflow files. So there is no way to directly specify action.yml as an argument of actionlint command.
https://github.com/rhysd/actionlint/releases/tag/v1.7.0

actionlint: revert including action files

---

flake-module.nix

Specify the default value of perSystem option treefmt as { } (an empty set) in the flake module.
Fix the "option treefmt used but not defined" error when importing the flake module without adding configurations.
The following check using @zarelit's reproducer shows that the errors disappear after applying this change:
```sh
nix flake show github:zarelit/repro-treefmt-issue-78 --override-input treefmt-nix github:ShamrockLee/treefmt-nix/fix-flake-module-empty
```
This pull request closes #78
Cc:
@zarelit
@zimbatm

flake-modules.nix: allow empty specification

---

module-options.nix

When using `lib.mkRenamedOptionModule`, the trace warning is emitted whenever the option is accessed.
Because we iterate and check the .enable option of all the programs, the renamed option gets accessed all the time.
So we check if the option is "visible" before checking in, which `lib.mkRenamedOptionModule` sets to false.
Fixes #211

fix: only eval enable option if visible

---

module-options.nix

Turns out not all options have the visible attribute.
Fixes https://github.com/numtide/treefmt-nix/pull/214#issuecomment-2282188773
/cc @phanirithvij

fixup! fix: only eval enable option if visible (#214)

---

examples/formatter-shellcheck.toml
examples/formatter-shfmt.toml
programs/shellcheck.nix
programs/shfmt.nix

So that e.g. `.envrc.recommended` gets processed.

{shellcheck,shfmt}: include `*.envrc.*` files

---

module-options.nix

When the `PRJ_ROOT` environment variable is set, [`treefmt` will use it to populate the `--tree-root` option](https://github.com/numtide/treefmt/blob/31e363dbc7d99e83e9924be21e9e169bbfea98f3/docs/usage.md?plain=1#L24).
Also, both `--tree-root` and `--tree-root-file` options must not be set at the same time, otherwise leading to:
```
treefmt: error: --tree-root and --tree-root-file can't be used together
```
As the tree-fmt module is explicitly setting `--tree-root-file`, I don't see a justification to let `PRJ_ROOT` leak in this script.

fix: unset PRJ_ROOT to prevent impure behavior

---

programs/mypy.nix

the code accidentially checked the wrong variable

mypy: fix python path not beeing set

---

flake.lock
flake.nix

This input is more appropriate since `treefmt-nix` is pulling in tools that don't benefit from the channel blockers of `nixos-*`.

inputs: use `nixpkgs-unstable` instead of `nixos-unstable`

---

examples/formatter-meson.toml
programs/meson.nix
programs/muon.nix

Fixes #241 
Previously the formatters only globbed the top-level files. I tried several different combos and found these work. The other globs I tried:
`*/meson.build`
`**/meson.build`
Did not work. But these seem to.

meson: format all meson files

---

examples/formatter-rustfmt.toml
flake.lock
programs/rustfmt.nix

Currently, rustfmt will recursively format module out of line files which is counter to the standards stated for formatters. I am hoping to get a response from the rustfmt folks in particular as to the expected way to handle this but this is the solution I found that works. 
If they get back to me, I will update this PR. Otherwise, this should prevent rustfmt from going off and doing it's own thing. Probably not a huge deal but did seem relevant.

rustfmt: add skip children

---

module-options.nix

this makes it easier to integrate this into none-ls. Since the currently generated wrapper conflicts with the already existing treefmt executable and it's hard to detect if it's either the program which needs a configfile or the wrapper created by treefmt-nix.
Will follow this up with a PR to none-ls for a builtin plugin and afterwards a PR to nixvim to add an option to easily enable that plugin :)

wrapper: add treefmt-nix executable to output

---

examples/formatter-buildifier.toml
programs/buildifier.nix

For https://bazel.build/external/module.

buildifier: include all .bazel files by default

---

examples/formatter-deno.toml
programs/deno.nix

See https://docs.deno.com/runtime/reference/cli/formatter/#supported-file-types.

deno: include more supported files by default

---

programs/stylua.nix

Added `settings` options, which produce an optional `stylua.toml` config
file for `stylua` to use.
This was inspired by the `programs/prettier.nix` module which has a
similar implementation for its `prettierrc.json` for `prettier` through
its `settings` options.
`includes` and `excludes` options were added to easily override the
default if desired, rather than having to go through
`settings.formatter.stylua` separately.
I also added myself to `meta.maintainers`.

stylua: add options: `settings`, `includes`, `excludes`; add to `meta.maintainers`

---

programs/just.nix

This just makes the formatter work for hidden justfiles, `.justfile`.

just: include .justfile

---

programs/nixpkgs-fmt.nix

It is as simple as the summary says.
I use `nixpkgs-fmt` in my Nix projects and the treefmt check for it generally fails in system configuration projects because of generated `hardware-configuration.nix` files not being formatted correctly, which are meant to not be modified manually.
This makes it straightforward to add exclusions, rather than having to go through `settings.formatter.nixpkgs-fmt.excludes` to do so.

nixpkgs-fmt: add `includes` and `excludes` options

---

programs/just.nix

https://github.com/numtide/treefmt-nix/pull/246 attempted to include `.justfile` files using a regex-style optional match `\.?`. However, treefmt2 uses a Glob data structure to represent include paths, not a regex. The glob library used (https://github.com/gobwas/glob) uses `?` as a single-character wildcard, meaning files matching `justfile` and `.justfile` are instead ignored.
From https://github.com/gobwas/glob/blob/master/readme.md
```
// create glob with single symbol wildcard
g = glob.MustCompile("?at")
g.Match("cat") // true
g.Match("fat") // true
g.Match("at") // false
```

just: fix includes config for both hidden and non-hidden justfiles

---

programs/google-java-format.nix

These are simple additions.
- `aospStyle`: For those that need 4-spaced indentation, rather than 2-spaced.
- `includes` && `excludes`: Exposed through `programs.google-java-format` rather
than only through `settings.formatter.google-java-format`.
I also added myself to the maintainers list.

google-java-format: add `aospStyle`, `includes`, `excludes`

---

programs/mypy.nix

We used to allow . and / in formatter names but no longer.

escape names in formatter names

---

programs/elm-format.nix

At least, I'm pretty sure this was a typo.

Fix typo: Biome -> elm-format

---

module-options.nix

This reverts commit a10a0cbe2196120aa90e4f86d459376e1d108d58.
This was originally added to make it easier to integrate treefmt-nix into none-ls. none-ls ended up implementing a different approach which doesn't need this wrapper script:
<https://github.com/nvimtools/none-ls.nvim/pull/192>.
In the interest of keeping things simple, I propose that we get rid of this wrapper.

Revert "wrapper: add treefmt-nix executable to output (#243)"

---

programs/dos2unix.nix

The package `dos2unix` doesn't have `meta.mainProgram`
defined since it includes several binaries.
At present `lib.getExe` was inferring that we wanted the
path to `dos2unix`.
Here we now specify that we want `dos2unix`, avoiding
what is specified in the evaluation warning:
> *evaluation warning:* `getExe`: Package "dos2unix-7.5.2" does not have
> the `meta.mainProgram` attribute. We'll assume that the main program
> has the same name for now, but this behavior is deprecated, because
> it leads to surprising errors when the assumption does not hold. If
> the package has a main program, please set `meta.mainProgram` in its
> definition to make this warning go away. Otherwise, if the package
> does not have a main program, or if you don't control its definition,
> use `getExe'` to specify …

dos2unix: explicitly set `mainProgram` to `dos2unix`

---

programs/mdformat.nix

Added options:
- `end-of-line`
- `number`
- `wrapper`
Added myself to maintainers list also.

mdformat: maintainer add; add settings: `end-of-line`, `number`, `wrapper`

---

README.md

Small nitpick I noticed while browsing the README.
[The current link leads to a broken page](https://treefmt.com/configure.html), but [this one](https://treefmt.com/latest/getting-started/configure/) looks fine.

Fix dead documentation link

---

examples/formatter-sqlfluff.toml
programs/sqlfluff.nix

Current `programs.sqlfluff.enable = true` enforces command-line option `--dialect=ansi`. This overrides project-level sqlfluff settings; for example, even if I have `pyproject.toml` with the following setting in a project filled with Databricks SQL files, `nix fmt` fails:
```toml
[tool.sqlfluff.core]
dialect = "databricks"
```
This PR removes the default option `--dialect=ansi`.

sqlfluff: disable default dialect

---

examples/formatter-clang-format.toml
programs/clang-format.nix

Clang-Format can format GLSL files too. Extensions are obviously GLSL as well as 
https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/
```
.vert - a vertex shader
.tesc - a tessellation control shader
.tese - a tessellation evaluation shader
.geom - a geometry shader
.frag - a fragment shader
.comp - a compute shader
```

All GLSL extensions to clangfmt

---

programs/rustfmt.nix

When I use the Rust toolchain installed from `rust-overlay` or `Fenix` I've got an error.
```
evaluation warning: getExe: Package rust-nightly-complete-with-components-2025-02-01 does not have the meta.mainProgram attribute. We'll assume that the main program has the same name for now, but this behavior is deprecated, because it leads to surprising errors when the assumption does not hold. If the package has a main program, please set `meta.mainProgram` in its definition to make this warning go away. Otherwise, if the package does not have a main program, or if you don't control its definition, use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
2025/02/10 00:56:39 INFO using config file: /nix/store/n65qj2fiz3f64smqffhqp54nimgp4ax4-treefmt.toml
Error: failed to …
```

rustfmt: fix for Rust packages from rust-overlay

---

module-options.nix

Fix: example of global.excludes

---

flake-module.nix

Passing a non-literal string to `example` or `defaultText` causes the docs to render the value using `lib.generators.toPretty`.
If you want to use markdown, use `literalMD`. If you want to pass a nix expression, use `literalExpression`.

fix defaultText for `pkgs` option using `literalMD`

---

programs/just.nix

Given the following projects:
```
.
├── foobar
│   └── justfile
└── justfile
```
the previous implementation would have just reformatted `./justfile` but not `./foobar/justfile`.
I also simplified the previous bash implementation by re-using mkFormatterModule

just: format justfile in subdirectories

---

programs/templ.nix

templ throws an error on format check that its missing the go binary.  im not sure if this its the right way to do it. for me it works fine. i also tested it with throwing a templ file in the repo and everything. error is gone after that.
```
nent {\n\treturn templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {\n\t\ttempl_7745c5c3_W, ctx := templ_7745c5c3_Inpu
t.Writer, templ_7745c5c3_Input.Context\n\t\tif templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {\n\t\t\treturn templ_7745c5c3_CtxErr\t\t}\n\t\ttempl_7745c5c3_Buffer, templ_7
745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)\n\t\tif !templ_7745c5c3_IsBuffer {\n\t\t\tdefer func() {\n\t\t\t\ttempl_7745c5c3_BufErr := …
```

templ: adds needed go pkg

---

examples/formatter-biome.toml
programs/biome.nix

This PR is meant to solve the issue mentioned here #378, about biome not sorting imports

bugfix: biome default organizeImports

---

README.md

It seems that the flake inputs in the documentation are missing [nix-systems/default](https://github.com/nix-systems/default) as an input for the flake. However, by referring to the implementation in [treefmt-nix/flake.nix](https://github.com/numtide/treefmt-nix/blob/main/flake.nix), I ultimately made the following change (as shown in the PR):
```nix
outputs = { self, nixpkgs, treefmt-nix }:
let
systems = [
"aarch64-darwin"
"aarch64-linux"
"x86_64-darwin"
"x86_64-linux"
];
eachSystem = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});
treefmtEval = eachSystem (pkgs: treefmt-nix.lib.evalModule pkgs ./treefmt.nix);
in
{
formatter = eachSystem (pkgs: treefmtEval.${pkgs.system}.config.build.wrapper);
checks = eachSystem (pkgs: {
formatting = …
```

README: update systems input in flakes example

---

examples/formatter-biome.toml
programs/biome.nix

I'm writing this PR because I noticed that the formatter is missing most of the options that Biome provides. I think it would be a lot easier for us if we didn't have to manually add our own options. Instead, I propose that we use free-field options and validate them against Biome's JSON schema.
I have also provided the option to set the command for biome and if it should process unsafe fixes.
I am not an expert of Nix, I tested locally and it is working correctly, but please let me know if any improvement is required

feat: use json schema for biome

---

examples/formatter-biome.toml
programs/biome.nix

Sorry, with the PR #391, I introduced an issue with biome v2+. The biome CLI refuses configuration if they do not have .json extension.

fix: biome config extension missing

---

README.md
programs/dockerfmt.nix

Adds [dockerfmt](https://github.com/reteps/dockerfmt), "a modern version of dockfmt".
Adds `-n` and `-w` args to write the file with a newline ending instead of just printing formatting changes.
It was [recently added to nixpkgs](https://github.com/NixOS/nixpkgs/pull/428515), so I needed to update `flake.lock`

feat: add dockerfmt formatter

---

programs/nixfmt-classic.nix

I found it annoying to always have this warning especially as I'm already explicitly opting to use this formatter and I thought that it would just add extra clutter to have an option to disable the warning

nixfmt-classic: remove warning
