numtide/treefmt-nix

README.md, programs/stylua.nix
Adds a module for lua formatting with `stylua`
=> feat: add stylua program module

README.md, programs/purs-tidy.nix
For formatting PureScript sources.
=> Add purs-tidy formatter module

README.md, programs/scalafmt.nix
Fixes https://twitter.com/volpegabriel87/status/1607714931021086722?s=20&t=5aAFiGogBS5VRXJwua1QfA
=> add scalafmt

flake-module.nix
See https://github.com/numtide/treefmt-nix/pull/14#issuecomment-1365944045
This effectively reverts #18
=> `flake-parts`: Remove top-level 'treefmt' package

README.md, flake.lock, programs/mdsh.nix, treefmt.nix
Depends on https://nixpk.gs/pr-tracker.html?pr=214439
=> new program: mdsh

module-options.nix
=> [schema]: Represent globals correctly

README.md, programs/hclfmt.nix
=> new program: hclfmt

flake-module.nix
=> flake-parts: Add `flakeCheck` option to disable adding check

module-options.nix
=> Added devShell in module-options build

programs/dprint.nix
Same comments from https://github.com/numtide/treefmt-nix/pull/103 apply so doing it here too
=> Clean up dprint integration

programs/prettier.nix
* Expose Prettier configuration options, taken from
http://json.schemastore.org/prettierrc
* Wrap Prettier invocation in a command that passes generated
configuration file from passed options
=> Expose Prettier configuration

flake.lock, programs/dprint.nix
=> Remove wrapper from dprint and pass generated config in settings instead

README.md
I rephrased the intro section to be more catchy and easier to understand the benefits for Nix beginners and people not having used treefmt before.
@zimbatm Ready for review.
Feel free to modify the PR, request changes or delete this PR.
=> Rephrase intro in README.md to focus on USPs

programs/yamlfmt.nix
=> yamlfmt also *.yml

programs/dprint.nix
... by making the `settings` option a freeformType.
Fixes #149.
=> feat(dprint): allow custom options for external formatters

README.md
Closes #189
Signed-off-by: Brian McGee <brian@bmcgee.ie>
=> doc: fix treefmt configuration link

examples/formatter-actionlint.toml, programs/actionlint.nix
Linting of actions was introduce in v1.7.0:
https://github.com/rhysd/actionlint/releases/tag/v1.7.0
Previously, actionlint only linted workflows.
=> actionlint: also lint action files

flake.lock
Brings in treefmt v2.0.4
Signed-off-by: Brian McGee <brian@bmcgee.ie>
=> feat: update nixpkgs input

README.md
Adjust the format a bit to be consistent with other projects
=> README: new format

module-options.nix
=> options: default projectRootFile to .git/config

examples/formatter-terraform.toml, programs/terraform.nix
=> 🆙 Include all opentofu-compatible files for Terraform

programs/just.nix
Include [just modules](https://github.com/casey/just#modules1190)
=> just: include just modules

programs/mypy.nix
fixes https://github.com/numtide/treefmt-nix/issues/247
=> mypy: fix recursive globbing

programs/dprint.nix
depends on https://github.com/NixOS/nixpkgs/pull/398815
I want to simplify this example ideally.
cc @zimbatm
=> programs.dprint: update plugins example

examples/formatter-biome.toml, examples/formatter-clang-format.toml, examples/formatter-deno.toml, examples/formatter-erlfmt.toml, examples/formatter-fourmolu.toml, examples/formatter-meson.toml, examples/formatter-ormolu.toml, examples/formatter-prettier.toml, flake.lock, programs/php-cs-fixer.nix
=> Update nixpkgs input

examples/formatter-rustfmt.toml, programs/rustfmt.nix
=> rustfmt: bump edition

examples/formatter-biome.toml, programs/biome.nix
* Add `*.css` to includes
* Add `settings.css.*` options (https://biomejs.dev/reference/configuration/#css)
* Change `--config-path` to use file instead of directory (changed in biomejs/biome#2419)
=> feat(biome): add css support
